# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0f79a42cabd3189b51be25f3d0161bbfe682b5071b1275efc00bb54c7749356c356d2c94c0d9ac85b4b7b1359780928655fe725de098e9b05af120291053dc3

test:
  secret_key_base: a6628b9c7545c82e75183a5846c7521ec909135d7e7b3e15334f22ba9e23c0a8e9aa76b2251725a0f329f08876a97d5b614f571b2e11da118180c129cc42ae41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
